## Numpy: Numpy is an external package which helps us to create C styled arrays, process the data and execute stuffs and used to deal with linear algebra aspects used in python

### here first we import our numpy package as np(alias) to use it
### np.array(): helps us to create arrays we want of any shape and size
### reshape(): helps us to change the dimmensions or the shape of an alraedy exsisting array

In [2]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,0])
vrr=arr.reshape(5,2)
print(vrr)
print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]
 [9 0]]
[1 2 3 4 5 6 7 8 9 0]


## 1. Indexing our arrays

In [2]:
import numpy as np

##### Here the astype() method converts the array from one datatype to another

In [2]:
a=np.array([1,2.5,7,8.8])
b=a.astype('int')

In [3]:
b

array([1, 2, 7, 8])

In [4]:
print(a[3])
print(b[3])

8.8
8


In [5]:
print(b[-3])

2


#### A simple program to find the elements of an array at the index given by the user using exception handling

In [9]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
try:
    print("enter the row and column of the element u want to view:")
    x=int(input())
    y=int(input())
    print(arr[x][y])
except IndexError as i:
    print(i)
    print("give valid indices")
except Exception as e:
    print(e)

enter the row and column of the element u want to view:
3
4
index 3 is out of bounds for axis 0 with size 3
give valid indices


In [10]:
arr[2][2]

9

## 2. Slicing our array

##### a. For 1d array

#### General syntax for slicing 1d arrays: arr[m : n : step ] 

In [11]:
arr=np.array([1,2,3,4,5,6,7,8,9])

In [12]:
print(arr[2:5])
print(arr[1:6:2])

[3 4 5]
[2 4 6]


In [13]:
print(arr[:6:2])
print(arr[::2])
print(arr[2::])
print(arr[::])

[1 3 5]
[1 3 5 7 9]
[3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


###### b. For 2d array 

#### General syntax for slicing 2d arrays: arr[ m: n: step1 , x: y: step2]

In [14]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
arr

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
print(arr[0,:])
print(arr[0:1,:])

[1 2 3]
[[1 2 3]]


In [16]:
print(arr[::2,::2])

[[1 3]
 [7 9]]


In [17]:
v=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [18]:
v[[0,1]]=v[[2,1]]
v

array([[7, 8, 9],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
print(arr[:,1::2])
print(arr[0:3,1])

[[2]
 [5]
 [8]]
[2 5 8]


In [20]:
print(arr[1:3,1:3])
print()
print(arr[1,1:3])

[[5 6]
 [8 9]]

[5 6]


###### c. Slicing our 3D array

#### we can acces the elements of 3d array as: arr[ depth_axis, row , column]

#### To slice 3d arrays: arr[ a: b: step1, x: y: step2, m: n: step3

In [21]:
arr=np.array([[[1,2],[3,4],[5,6]],
             [[7,8],[9,10],[11,12]],
             [[13,14],[15,16],[17,18]]])

In [22]:
arr

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]]])

In [23]:
arr[0,0,0]

1

In [24]:
print(arr[0,2,:])

[5 6]


In [25]:
print(arr[1:,0:2,:])

[[[ 7  8]
  [ 9 10]]

 [[13 14]
  [15 16]]]


## 3. Creating arrays using various numpy methods

#### a. Creating arrays of zeroes using  .zeros( ( shape ), dtype)

In [2]:
np.zeros((2,2),dtype='complex')

array([[0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j]])

#### b. Creating arrays of 1 using  .ones( ( shape ) , dtype)

In [3]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [4]:
np.ones((2,3),dtype='str')

array([['1', '1', '1'],
       ['1', '1', '1']], dtype='<U1')

#### c. Creating arrays of random numbers using  .random.rand(size)

In [5]:
np.random.rand(3,2)

array([[0.16471286, 0.09568188],
       [0.41718609, 0.62388437],
       [0.36001523, 0.65324927]])

#### d. Creating array of any number of our choice using the .full( (size) , number)

In [6]:
np.full((2,3),69)

array([[69, 69, 69],
       [69, 69, 69]])

#### e. Creating equally spaced arrays using: .arange( start , stop , dev , dtype)

In [7]:
np.arange(2,10,2)

array([2, 4, 6, 8])

In [8]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [9]:
np.arange(2,12,2,dtype='complex')

array([ 2.+0.j,  4.+0.j,  6.+0.j,  8.+0.j, 10.+0.j])

#### f. Creating identity matrix using the .eye( rows , dtype) method

In [4]:
my_mat=np.eye(6,dtype=int)
print(my_mat)
print()
n=my_mat.reshape(4,9)
print(n)

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]

[[1 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 1]]


## 4. Flatten, ravel,transpose of matrix created using numpy

#### a. flatten and ravel methods:

#### flatten(): returns a copy of 1d array taken from the array calling it and this copy is stored in some other locations and not referencing the original array

#### ravel(): returns a 1d array referencing the original array calling it and any changes made to the array returned by ravel would be reflected too in the original array also

In [11]:
a=np.full((2,2),69)
print(a)

[[69 69]
 [69 69]]


In [13]:
b=a.flatten()
print(b)

[69 69 69 69]


In [14]:
c=a.ravel()
print(c)

[69 69 69 69]


In [16]:
a=np.full((2,2),69,dtype='float')
print(a)
b=a.flatten()
print(b)
c=a.ravel()
print(c)
print("original array:",a)
c[2]=619
print(c)
print("original array:",a)

[[69. 69.]
 [69. 69.]]
[69. 69. 69. 69.]
[69. 69. 69. 69.]
original array: [[69. 69.]
 [69. 69.]]
[ 69.  69. 619.  69.]
original array: [[ 69.  69.]
 [619.  69.]]


In [19]:
d=b.flatten()
d

array([69., 69., 69., 69.])

#### b. transpose of a matrix: by transposing a matrix we can interchange the rows and columns of a matrix in python using .transpose() method

In [2]:
a=np.array([[1,7,9],
           [2,3,4]])
print("original array:\n",a)
b=a.transpose()
print("transposed matrix:\n",b)
b[2][1]=6
print("transposed matrix:\n",b)
print("original matrix is:\n",a)

original array:
 [[1 7 9]
 [2 3 4]]
transposed matrix:
 [[1 2]
 [7 3]
 [9 4]]
transposed matrix:
 [[1 2]
 [7 3]
 [9 6]]
original matrix is:
 [[1 7 9]
 [2 3 6]]


### 5. Reversing a 2d array using different methods:

##### a. Using slicing mechanism

In [7]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
print("\n")
b=arr[::-1,-1::-1]
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


[[10  9  8  7  6]
 [ 5  4  3  2  1]]


#### b. Using the built in flip( arr , axis ) method

In [9]:
print(np.flip(arr,axis=1))
print()
print(np.flip(arr,axis=0))

[[ 5  4  3  2  1]
 [10  9  8  7  6]]

[[ 6  7  8  9 10]
 [ 1  2  3  4  5]]


In [10]:
b=np.flip(np.flip(arr,axis=1),axis=0)
print(b)

[[10  9  8  7  6]
 [ 5  4  3  2  1]]


## 6. Stacking and concatenating numpy arrays:

#### a. Using the dstack( ) method: where arrays are stacked based on indices along thew depth axis 

In [5]:
a=np.array([1,2,3,4,5])
b=np.array([5,6,7,8,9])
c=np.dstack((a,b))
print(c)

[[[1 5]
  [2 6]
  [3 7]
  [4 8]
  [5 9]]]


In [6]:
a1=np.array([[1,2],[3,4]])
a2=np.array([[5,6],[7,8]])
c1=np.dstack((a1,a2))
print(c1)
print(c1.size)
print(c1.shape)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]
8
(2, 2, 2)


#### b. Using the vstack( ) method : where arrays are stacked vertically

In [7]:
print(np.vstack((a,b)))

[[1 2 3 4 5]
 [5 6 7 8 9]]


##### c. Using the hstack( ) method : where the arrays are stacked horizontally

In [8]:
print(np.hstack((a,b)))

[1 2 3 4 5 5 6 7 8 9]


#### c. concatenate( ) : helps us to concatenate or add arrays to an exsisting array along any axis as we want

In [9]:
a1=np.array([[1,2],[3,4]])
a2=np.array([[5,6],[7,8]])
a3=np.concatenate((a1,a2),axis=0)
print(a3)
a4=np.concatenate((a1,a2),axis=1)
print()
print(a4)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[[1 2 5 6]
 [3 4 7 8]]


### 7. Basic arithmetic operations on NumPy arrays: The basic arithmetic operations can easily be performed on NumPy arrays. The important thing to remember is that these simple arithmetics operation symbols just act as wrappers for NumPy ufuncs.

##### a. Here we are going to perform some of the basic stuffs like add, substract, multiplication, divide, power, remainder. 

In [10]:
a= np.array([[1,2,3,4],[5,6,7,8]])
print(a)

[[1 2 3 4]
 [5 6 7 8]]


In [12]:
print("addition:", a+10,"\n")
print("substraction:", a-10,"\n")
print("multiplication:", a*10,"\n")
print("division:", a/10,"\n")
print("remainder:",a%10,"\n")
print("power:", a**2,"\n")

addition: [[11 12 13 14]
 [15 16 17 18]] 

substraction: [[-9 -8 -7 -6]
 [-5 -4 -3 -2]] 

multiplication: [[10 20 30 40]
 [50 60 70 80]] 

division: [[0.1 0.2 0.3 0.4]
 [0.5 0.6 0.7 0.8]] 

remainder: [[1 2 3 4]
 [5 6 7 8]] 

power: [[ 1  4  9 16]
 [25 36 49 64]] 



#### b. Mean, Median and Standard deviation
#### To find the mean , median and standard deviation of a NumPy array, use the mean(), std() and median() methods:

In [23]:
# this gives mean of all the columns (axis=0)
print("mean of the columns of array a:", np.mean(a,axis=0))

mean of the columns of array a: [3. 4. 5. 6.]


In [24]:
# this gives median of all the rows (axis=1)
print("median of the rows of array a:", np.median(a,axis=1))

median of the rows of array a: [2.5 6.5]


In [25]:
# this gives mean and median of the whole array
print("median of the array a:", np.median(a))
print("mean of the array a:", np.mean(a))

median of the array a: 4.5
mean of the array a: 4.5


In [26]:
print("standard deviation of the array:", np.std(a))

standard deviation of the array: 2.29128784747792


#### c. Applying Linear Algebra operations :

In [28]:
a = np.array([[6, 1, 1],
[4, -2, 5],
[2, 8, 7]])
print(a)

[[ 6  1  1]
 [ 4 -2  5]
 [ 2  8  7]]


In [41]:
print( "rank of matrix:", np.linalg.matrix_rank(a) )
print( "trace of matrix:", np.trace(a) )
print( "determinent of matrix:", np.linalg.det(a) ,"\n")
print( "inverse of matrix:", np.linalg.inv(a) )

rank of matrix: 3
trace of matrix: 11
determinent of matrix: -306.0 

inverse of matrix: [[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


#### d. Min-Max values and their indexes
#### Min and Max values in an array can be easily found using the min() and max() methods:

In [43]:
a = np.array([[6, 1, 1],
[4, -2, 5],
[2, 8, 7]])
print(a)

[[ 6  1  1]
 [ 4 -2  5]
 [ 2  8  7]]


In [47]:
print("maximum element of the array:", np.max(a))
print("minimum element of the array:", np.min(a), "\n")

maximum element of the array: 8
minimum element of the array: -2 



In [50]:
# when axis=0: it works with columns 
# when axis=1: it works with rows
print("maximum element of rows of the array:", np.max(a,axis=1))
print("minimum element of the columns of the array:", np.min(a,axis=0))

maximum element of rows of the array: [6 5 8]
minimum element of the columns of the array: [ 2 -2  1]


### 8. Sorting in NumPy arrays
### For any programmer, the time complexity of any algorithm is of prime essence. Sorting is an important and very basic operation that you might well use on a daily basis as a data scientist. So, it is important to use a good sorting algorithm with minimum time complexity.
### The Numpy library has a range of sorting functions that you can use to sort your array elements. It has implemented quicksort, heapsort, mergesort, and timesort for you under the hood when you use the sort() method:

In [52]:
a=np.array([1,4,2,5,3,6,8,7,9])
print(a)

[1 4 2 5 3 6 8 7 9]


In [55]:
b=np.sort(a,kind='heapsort')
print("heap sorting:",b)

heap sorting: [1 2 3 4 5 6 7 8 9]


In [54]:
c=np.sort(a,kind='quicksort')
print("quick sorting:" ,c)

quick sorting: [1 2 3 4 5 6 7 8 9]


#### a. We can also sort the data as we wish i.e. along the rows(axis=0) or along the columns  ( axis= 1).

In [56]:
a = np.array([[5,6,7,4],
              [9,2,3,7]])
# sort along the column
print('Sort along column :','\n',np.sort(a, kind='mergresort',axis=1))
# sort along the row
print('Sort along row :','\n',np.sort(a, kind='mergresort',axis=0))

Sort along column : 
 [[4 5 6 7]
 [2 3 7 9]]
Sort along row : 
 [[5 2 3 4]
 [9 6 7 7]]


### 9. NumPy arrays and Images

#### Images are made up of pixels that are stored in the form of an array. Each pixel has a value ranging between 0 to 255 – 0 indicating a black pixel and 255 indicating a white pixel. A colored image consists of three 2-D arrays, one for each of the color channels: Red, Green, and Blue, placed back-to-back thus making a 3-D array. Each value in the array constitutes a pixel value. So, the size of the array depends on the number of pixels along each dimension.

##### This is a good start. Matplotlib has its own module for handling images, and you’re going to lean on that because it makes straightforward to read and write image formats.

#### If you run this code, then your friend the NumPy array will appear in the output:

In [15]:
import numpy as np
import matplotlib.image as mpimg
img = mpimg.imread("cat.jpg.jpg")
print(type(img))
print(img.shape)

<class 'numpy.ndarray'>
(612, 408, 3)


##### This is a simple code to display the original image

In [27]:
from IPython.display import Image
Image(url= "cat.jpg.jpg", width=209, height=50)

###### a. Want to see what happens when you drop out the R and G channels?

In [19]:
output = img.copy()  # The original image is read-only!
output[:, :, :2] = 0
mpimg.imsave("blue1.jpg", output)

###### We get an image consisting of only blue channel and the image appares to be blue

In [28]:
from IPython.display import Image
Image(url= "blue1.jpg", width=200, height=50)

#### b. Lets now create a black and white image of our cat

###### But now, it’s time to do something a little more useful. You’re going to convert this image to grayscale. However, converting to grayscale is more complicated. Averaging the R, G, and B channels and making them all the same will give you an image that’s grayscale. 
###### You can specify a color map, known as a cmap in the Matplotlib world. If you specify a cmap, then Matplotlib will handle the linear gradient calculations for you.
###### These new lines create a new array called averages, which is a copy of the img array that you’ve flattened along axis 2 by taking the average of all three channels. You’ve averaged all three channels and outputted something with R, G, and B values equal to that average. When R, G, and B are all the same, the resulting color is on the grayscale.

In [29]:
averages = img.mean(axis=2)  # Take the average of each R, G, and B
mpimg.imsave("black-white.jpg", averages, cmap="gray")

##### displaying the black and white image:

In [31]:
Image(url= "black-white.jpg", width=200, height=50)

###### 

### 10. Masking with NumPy arrays:  basically what masking does is that if we apply some logical conditions to our array , then an array corresponding to this values having True - False values would be created as a mask.
### Now if we want to retrieve the elements from the original array whic sattisfies our condition then we can simply use this mask array which would return a 1d array where itv gives the elements corresponding to only True values.

#### Lets consider an example where we have a 2d array containing marks and want to retrieve only those marks whic are greater than the passing marks 36:

In [32]:
arr= np.array([[16 , 12 , 10 , 65 , 34, 36 ],
               [20 , 50 , 72 , 69 , 22 , 52],
               [65 , 44 , 42 , 35 , 12 , 29],
               [70 , 63 , 67 , 45 , 16 , 37]])
# applying our mask
mask = arr > 36

In [33]:
print("Our msked array looks like this:")
print(mask)

Our msked array looks like this:
[[False False False  True False False]
 [False  True  True  True False  True]
 [ True  True  True False False False]
 [ True  True  True  True False  True]]


In [36]:
arr1= arr[mask]
print("required results are as follows:\n")
print(arr1)

required results are as follows:

[65 50 72 69 52 65 44 42 70 63 67 45 37]


#### And that's potentially enough to get started and master the NumPy libraries.... And wish everyone good luck in their coding journey....cheers